@baseUrl=http://localhost:3000
@createdHostId = {{createHost.response.body.$.id}}
@token = {{signin.response.body.$.token}}
@userId = {{userMe.response.body.$.id}}

### Create Host

# @name createHost
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Joanderson",
  "email": "teste1@gmail.com",
  "password": "123"
}

### Read Hosts

GET {{baseUrl}}/user
Authorization: bearer {{token}}

### Read a host


### Reads Hosts

GET {{baseUrl}}/users/emails

### Reads a host


### Reads Hosts

GET {{baseUrl}}/emails

### Reads a host



GET {{baseUrl}}/signin
Authorization: bearer {{token}}
###

GET {{baseUrl}}/user/{{createdHostId}}
Authorization: bearer {{token}}

### Update a host

PUT {{baseUrl}}/User/{{createdHostId}}
Authorization: bearer {{token}}
Content-Type: application/json

{
  "name": "Google Search",
  "address": "www.google.com"
}

### Delete a host



### Update a host

PUT {{baseUrl}}/user/update_user/3
Content-Type: application/json

{ 
  "password": "123"
}

### Delete a host

DELETE {{baseUrl}}/User/{{createdHostId}}
Authorization: bearer {{token}}

### Create reachability

POST {{baseUrl}}/User/{{createdHostId}}/reachabilities
Authorization: bearer {{token}}

### Read reachabilities by Host

GET {{baseUrl}}/user/{{createdHostId}}/reachabilities
Authorization: bearer {{token}}

### Read all reachabilities

GET {{baseUrl}}/reachabilities
Authorization: bearer {{token}}

### Create User

# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Carlos",
  "email": "carlos@email.com",
  "password": "123",
  "confirmationPassword": "123"
}

### Signin Ok

# @name signin
POST {{baseUrl}}/signin
Content-Type: application/json

{
  "email": "joanderson@gmail.com",
  "password": "123"
}

### Signin fail

POST {{baseUrl}}/signin
Content-Type: application/json

{
  "email": "teste1@gmail.com",
  "password": "123"
}

### Read User (with token)

# @name userMe
GET {{baseUrl}}/users/me
Authorization: bearer {{token}}