@server = http://localhost:3000

### GET /

GET {{server}}/

### GET /ola

GET {{server}}/users

### GET /hello/en

GET {{server}}/person

### GET /hello/en with bad request

GET {{server}}/hello/en

### GET /hello/pt/:name

GET {{server}}/users/1

### GET /hello/pt/:name with bad request

GET {{server}}/hello/pt/

### POST /hello/es - Convert to Lowercase

POST {{server}}/users
Content-Type: application/json
{
  "name": "LoRem IPSUM"
}

###

### POST /hello/es - Convert to Uppercase

POST {{server}}/util/text/uppercase
Content-Type: application/json

{
  "name": "LoRem IPSUM"
}

###

### POST /hello/es with bad request - Minimum

POST {{server}}/util/text/minimum
Content-Type: application/json

{
  "name": ["10", "5", "2"] 
}

###

### POST /hello/es with bad request - Maximum

POST {{server}}/util/text/maximum
Content-Type: application/json

{
  "name": ["10", "5", "2"] 
}

###

### POST /hello/es

POST {{server}}/users

### GET /hello/fr (404)

GET {{server}}/hello/fr